version: "3.9"

services:
  fastapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api-container
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./API:/app