version: "3.9"

services:
  db:
    image: mysql:8.0.36
    platform: linux/amd64
    container_name: db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
    restart: always

  fastapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api-container
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./API:/app